Update docker-push.yml

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -6,17 +6,17 @@ on:
       ROCM_REPO:
         description: 'rocm repo'
         required: true
-        default: 6.0
+        default: '6.0'
         
       ROCM_VERSION:
         description: 'rocm-ver'
         required: true
-        default: 6.0.0
+        default: '6.0.0'
         
       ROCM_LIB_VERSION:
         description: 'rocm-lib-ver'
         required: true
-        default: 600
+        default: '60000'
         
       ROCM_PATH:
         description: 'rocm-path'
@@ -29,12 +29,12 @@ on:
   
 jobs:
   build:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
 
     env:
-      ROCM_REPO: 6.0
-      ROCM_VERSION: 6.0.0
-      ROCM_LIB_VERSION: 60000
+      ROCM_REPO: '6.0'
+      ROCM_VERSION: '6.0.0'
+      ROCM_LIB_VERSION: '60000'
       ROCM_PATH: /opt/rocm-6.0.0
       
     steps:
@@ -55,17 +55,17 @@ jobs:
             echo "Docker is already installed."
           fi
 
-    - name: Set up Docker Buildx
-      run: |
-          # Check if Docker Buildx is installed
-          if ! docker buildx version &> /dev/null; then
-            echo "Docker Buildx not found. Installing Docker Buildx..."
-            mkdir -p ~/.docker/cli-plugins/
-            curl -L https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
-            chmod +x ~/.docker/cli-plugins/docker-buildx
-          else
-            echo "Docker Buildx is already installed."
-          fi
+   # - name: Set up Docker Buildx
+   #   run: |
+   #       # Check if Docker Buildx is installed
+   #      if ! docker buildx version &> /dev/null; then
+   #         echo "Docker Buildx not found. Installing Docker Buildx..."
+   #         mkdir -p ~/.docker/cli-plugins/
+   #         curl -L https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
+   #         chmod +x ~/.docker/cli-plugins/docker-buildx
+   #       else
+   #         echo "Docker Buildx is already installed."
+   #       fi
       
     - name: Login to dockerhub
       uses: docker/login-action@v2
@@ -82,13 +82,13 @@ jobs:
           fi
           echo "IMAGE_TAG=${unique_tag}" >> $GITHUB_ENV
           
-          docker buildx build \
+          docker build \
             --tag nlingamp/pt-github:${unique_tag} \
             --file Dockerfile \
             .
 
-    - name: Push Docker image to Docker Hub
-      run: |
-        docker push nlingamp/pt-github:${{ env.IMAGE_TAG }}
+   # - name: Push Docker image to Docker Hub
+    #  run: |
+       # docker push nlingamp/pt-github:${{ env.IMAGE_TAG }}
     
         
