Update json-Input4.yml

diff --git a/.github/workflows/json-Input4.yml b/.github/workflows/json-Input4.yml
--- a/.github/workflows/json-Input4.yml
+++ b/.github/workflows/json-Input4.yml
@@ -128,7 +128,8 @@ jobs:
           version_details_string+="}"
           
           #Printing the generated data
-          echo '{
+          json_data=$(cat <<EOF
+          {
                   "schema_version": "'"$schema_version"'",
                   "submit_date": "'"$submit_date"'",
                   "component": "'"$component"'",
@@ -149,4 +150,49 @@ jobs:
                   "rocm_cuda_score_details": '"$rocm_cuda_score_details"',
                   "rocm_score_details": '"$rocm_score_details"',
                   "cuda_score_details": '"$cuda_score_details"'
-          }' > docker/sample.json
+          }
+          EOF
+          )
+
+          # print json data output to file
+          echo "$json_data"
+          echo "$json_data" > /tmp/sample1.json
+      
+      # search $component $version
+      - name: Search for Pattern
+        id: search_pattern
+        run: |
+          # Define the file to read and the pattern to search for
+          FILE_PATH="/tmp/sample1.json"
+          LATEST_PATH="docker/rocm/ubuntu22/6.0"
+          STABLE_PATH="docker/ubuntu22/rocm-6.2"
+
+          # Check if the pattern is found in the file
+          if grep -q '"version": "latest"' "$FILE_PATH"; then
+            echo "Version is 'latest'. Moving file to latest"
+            
+            # Copy the file to the target directory
+            cp "$FILE_PATH" "$LATEST_PATH/"
+            
+          elif
+            echo "Version is not latest, Moving file to stable"
+            # Copy the file to the target directory
+            cp "$FILE_PATH" "$STABLE_PATH/"
+          else
+            echo "version not found"
+          fi
+      
+      - name: Verify File Move
+        run: |
+          FILE_NAME=$(/tmp/sample1.json)
+          TARGET_PATH="docker/rocm/ubuntu22/6.0" # Adjust if needed
+          if [ -f "$LATEST_PATH/$FILE_NAME" ]; then
+            echo "File successfully moved to $LATEST_PATH."
+          elif [ -f "$STABLE_PATH/$FILE_NAME" ]; then
+            echo "File is moved to $STABLE_PATH."
+          else
+            echo "file is not found"
+            exit 1
+          fi
+
+          
