Update ping.servers.yml

diff --git a/.github/workflows/ping.servers.yml b/.github/workflows/ping.servers.yml
--- a/.github/workflows/ping.servers.yml
+++ b/.github/workflows/ping.servers.yml
@@ -30,13 +30,13 @@ jobs:
       - name: Install Ansible
         run: |
           python -m pip install --upgrade pip
-          pip install ansible
+          pip install ansible 
       
       - name: Ping servers
         id: ping_servers
         run: |
           # Run the Ansible ping module and capture the output
-          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $GITHUB_WORKSPACE/ping_results.txt || echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
+          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $GITHUB_WORKSPACE/ping_results.txt 2>&1 #|| echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
           cat $GITHUB_WORKSPACE/ping_results.txt
 
       - name: Process Ping Results
