Update ping-servers-3.yml

diff --git a/.github/workflows/ping-servers-3.yml b/.github/workflows/ping-servers-3.yml
--- a/.github/workflows/ping-servers-3.yml
+++ b/.github/workflows/ping-servers-3.yml
@@ -29,7 +29,7 @@ jobs:
         id: ping_servers
         run: |
           # Run the Ansible ping module and capture the output
-          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > tee ping_results.txt || echo "Ping failed" >> ping_results.txt
+          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o >> tee ping_results.txt || echo "Ping failed" >> ping_results.txt
           
       - name: Process Ping Results
         run: |
