Update ping-server2.yml

diff --git a/.github/workflows/ping-server2.yml b/.github/workflows/ping-server2.yml
--- a/.github/workflows/ping-server2.yml
+++ b/.github/workflows/ping-server2.yml
@@ -48,6 +48,15 @@ jobs:
       - name: Filter Non-Responding Servers
         run: |
           grep 'Failed' ping_results.txt > failed_servers.txt
+          if [ $? -ne 0 ]; then
+              echo "grep command failed."
+              exit 1
+          fi
+
+          # Debug: Print contents of failed_servers.txt
+          echo "Contents of failed_servers.txt:"
+          cat failed_servers.txt
+          
           if [ -s failed_servers.txt ]; then
               echo "Sending email with the list of non-responding servers."
           else [ -s failed_servers.txt ]; then
