Update ping.servers.yml

diff --git a/.github/workflows/ping.servers.yml b/.github/workflows/ping.servers.yml
--- a/.github/workflows/ping.servers.yml
+++ b/.github/workflows/ping.servers.yml
@@ -12,14 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      #- run: |
-             #sudo apt install -y software-properties-common sshpass python3-pip
-             #python3 -m pip install virtualenv
-             #pip3 install -r requirements.txt
-      #- run: |
-         #chmod +x venv_setup.sh
-         #./venv_setup.sh
-      #- run: source venv/bin/activate
+
       - run: ls -lart 
 
       - name: Set up Python
@@ -30,32 +23,21 @@ jobs:
       - name: Install Ansible
         run: |
           python -m pip install --upgrade pip
-          pip install ansible 
+          pip install ansible
       
       - name: Ping servers
         id: ping_servers
         run: |
           # Run the Ansible ping module and capture the output
-          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $temp_file 
-          # || echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
-          mv $temp_file ping_results.txt
-          cat ping_results.txt
-
+          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $GITHUB_WORKSPACE/ping_results.txt || echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
+          cat $GITHUB_WORKSPACE/ping_results.txt
       - name: Process Ping Results
         run: |
           # Check for successful pings and failed pings
-          grep 'SUCCESS' ping_results.txt | awk '{print $1, "Online"}' > final_results.txt 
+          grep 'SUCCESS' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Online"}' > $GITHUB_WORKSPACE/final_results.txt 
           echo "final results"
-          cat final_results.txt
+          cat $GITHUB_WORKSPACE/final_results.txt
           
-          grep 'Failed' ping_results.txt | awk '{print $1, "Offline"}' >> final_results.txt
+          grep 'Failed' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Offline"}' >> $GITHUB_WORKSPACE/final_results.txt
           echo "final results-2"
-          cat final_results.txt
-
-      - name: Upload Ping Results
-        uses: actions/upload-artifact@v3
-        with:
-          name: ping-results
-          path: final_results.txt
-          
-      - run: cat final_results.txt
+          cat $GITHUB_WORKSPACE/final_results.txt
