Update rocm-ub22.yml

diff --git a/.github/workflows/rocm-ub22.yml b/.github/workflows/rocm-ub22.yml
--- a/.github/workflows/rocm-ub22.yml
+++ b/.github/workflows/rocm-ub22.yml
@@ -38,18 +38,31 @@ jobs:
     
     - name: Set up Docker
       run: |
-          # Check if Docker is installed
-          if ! command -v docker &> /dev/null; then
-            echo "Docker not found. Installing Docker..."
-            sudo apt-get update
-            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
-            sudo apt-get update
-            sudo apt-get install -y docker-ce
-          else
-            echo "Docker is already installed."
-          fi
+        # Check if Docker is installed
+        if ! command -v docker &> /dev/null; then
+          echo "Docker not found. Installing Docker..."
+          
+          # Update package list
+          sudo apt-get update -y
+
+          # Install dependencies
+          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+
+          # Add Docker's official GPG key
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+
+          # Set up the Docker repository
+          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+
+          # Update package list again
+          sudo apt-get update -y
+
+          # Install Docker
+          sudo apt-get install -y docker-ce
+
+        else
+          echo "Docker is already installed."
+        fi
       
     - name: Login to dockerhub
       uses: docker/login-action@v2
