Update rocm-ub22.yml

diff --git a/.github/workflows/rocm-ub22.yml b/.github/workflows/rocm-ub22.yml
--- a/.github/workflows/rocm-ub22.yml
+++ b/.github/workflows/rocm-ub22.yml
@@ -10,8 +10,32 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     
+    - name: Set up Docker
+      run: |
+          # Check if Docker is installed
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing Docker..."
+            sudo apt-get update
+            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+            sudo apt-get update
+            sudo apt-get install -y docker-ce
+          else
+            echo "Docker is already installed."
+          fi
+
     - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
+      run: |
+          # Check if Docker Buildx is installed
+          if ! docker buildx version &> /dev/null; then
+            echo "Docker Buildx not found. Installing Docker Buildx..."
+            mkdir -p ~/.docker/cli-plugins/
+            curl -L https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
+            chmod +x ~/.docker/cli-plugins/docker-buildx
+          else
+            echo "Docker Buildx is already installed."
+          fi
     
     - name: Login to dockerhub
       uses: docker/login-action@v2
@@ -34,7 +58,7 @@ jobs:
           --tag amddcgpuce/rocm:6.0.0-ub22 \
           --tag nlingamp/pt-github:${unique_tag} \
           -f rocm.ub22.Dockerfile \
-          .
+          --push .
    
-    - name: Push Docker image to Docker Hub
-      run: docker push nlingamp/pt-github:${unique_tag}
+    #- name: Push Docker image to Docker Hub
+    # run: docker push nlingamp/pt-github:${unique_tag}
