Update rocm-ub22.yml

diff --git a/.github/workflows/rocm-ub22.yml b/.github/workflows/rocm-ub22.yml
--- a/.github/workflows/rocm-ub22.yml
+++ b/.github/workflows/rocm-ub22.yml
@@ -57,23 +57,35 @@ jobs:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
     
-    - name: Build the Docker image
-      id: set_tag
+    - name: Create unique tag and build Docker image
+      id: build
+      env:
+        IMAGE_TAG_INPUT: ${{ github.event.inputs.image_tag }}
       run: |
-          # creating unique tag and parameterized
-          unique_tag=rocm-ub-22-$(date +%Y%m%d%H%M%S)
+          # Generate a unique tag if none is provided
+          if [ -z "$IMAGE_TAG_INPUT" ]; then
+            unique_tag="rocm-ub-22-$(date +%Y%m%d%H%M%S)"
+          else
+            unique_tag="$IMAGE_TAG_INPUT"
+          fi
+
+          # Ensure the tag is valid
+          if [[ ! "$unique_tag" =~ ^[a-zA-Z0-9_/-]+$ ]]; then
+            echo "Invalid tag format: $unique_tag"
+            exit 1
+          fi
+
+          echo "IMAGE_TAG=${unique_tag}" >> $GITHUB_ENV
           
-          #Building docker image
+          # Build Docker image with the unique tag
           docker build \
-            --no-cache \
-            --build-arg rocm_repo=${{ env.ROCM_REPO }} \
-            --build-arg rocm_version=${{ env.ROCM_VERSION }} \
-            --build-arg rocm_lib_version=${{ env.ROCM_LIB_VERSION }} \
-            --build-arg rocm_path=${{ env.ROCM_PATH }} \
-            --tag nlingamp/pt-github:${unique_tag} \
-            --file rocm.ub22.Dockerfile \
+            --build-arg ROCM_REPO=${{ env.ROCM_REPO }} \
+            --build-arg ROCM_VERSION=${{ env.ROCM_VERSION }} \
+            --build-arg ROCM_LIB_VERSION=${{ env.ROCM_LIB_VERSION }} \
+            --build-arg ROCM_PATH=${{ env.ROCM_PATH }} \
+            -t your-repo/pt-github:${unique_tag} \
             .
 
     - name: Push Docker image to Docker Hub
       run: |
-        docker push nlingamp/pt-github:${unique_tag}
+          docker push your-repo/pt-github:${{ env.IMAGE_TAG }}
